openapi: 3.0.0
info:
  title: Shop API
  description: This is a simple API for products and categories
  version: 1.0.0
servers:
  - url: http://localhost:3000
paths:
  /products:
    get:
      summary: Get all products
      responses:
        '200':
          description: A list of products
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    product_id:
                      type: integer
                    name:
                      type: string
                    description:
                      type: string
                    price:
                      type: number
                      format: float
                    stock_quantity:
                      type: integer
                    category_id:
                      type: integer
  /categories:
    get:
      summary: Get all categories
      responses:
        '200':
          description: A list of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    category_id:
                      type: integer
                    name:
                      type: string
                    description:
                      type: string
  /product_images:
    get:
      summary: Get all product images
      responses:
        '200':
          description: A list of product images
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    image_id:
                      type: integer
                    product_id:
                      type: integer
                    image_url:
                      type: string
