openapi: 3.0.0
info:
  title: Product Image API
  description: API for managing and retrieving product images
  version: 1.0.0
servers:
  - url: http://localhost:5000
    description: Local server

paths:
  /product_images:
    get:
      summary: Get all product images
      responses:
        '200':
          description: A list of product images
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ProductImage'
        '500':
          description: Internal server error

  /product_images/{id}:
    get:
      summary: Get a product image by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
          description: ID of the product image to retrieve
      responses:
        '200':
          description: A product image
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProductImage'
        '404':
          description: Product image not found
        '500':
          description: Internal server error

components:
  schemas:
    ProductImage:
      type: object
      properties:
        image_id:
          type: integer
          example: 1
        image_title:
          type: string
          example: "Example Image"
        image_url:
          type: string
          example: "http://example.com/image.jpg"
